# Generated by Django 5.2.5 on 2025-08-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keys',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
